classroom-dashboard/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # nested routes so student always belongs to section
  resources :sections do
  resources :students
  end

  resources :uploads

  # necessary for dropzone to work, however this means that /uploads is a viable link which we don't want. TODO: address this
  post '/uploads' => 'uploads#create'

  root 'sections#index'

  get 'sections/:id/flashcards', to: "sections#flashcards", as: :section_flashcards

  get 'sections/:id/quiz', to: "sections#quiz", as: :section_quiz

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

classroom-dashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S.P.A.M.</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag asset_path('cilantro.png'), :rel => 'icon', :type =>  'image/png' %>

    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta charset="UTF-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>

    <!-- top navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <% if admin_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <!-- deleted user sign in check (see above)  -->
            <li><%= link_to "SIGN OUT", destroy_admin_session_path, method: :delete %></li>
          </ul>

          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "MY SECTIONS", root_path, class: "navbar-brand"%></li>
          </ul>

        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%=link_to "SIGN UP", new_admin_registration_path %></li>
            <li><%= link_to "LOGIN", new_admin_session_path%></li>
          </ul>
        <% end %>

        <div class="navbar-header">
          <%= link_to "S.P.A.M.", root_path, class: "navbar-brand" %>
        </div>
      </div>
    </nav>

    <!-- cilantro logo -->
    <div class="cilantro-navbar">
      <%= image_tag("cilantro.png", :alt => "rss feed") %>
      <%= link_to image_tag("cilantro.png"), "https://giphy.com/gifs/spam-xdnytp8742kg0/fullscreen" %>
    </div>

    <!-- horizontal line -->
    <hr style="height:11px;background-color:purple">
    <br>

    <%= yield %>
  </body>
</html>