classroom-dashboard/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # nested routes so student always belongs to section
  resources :sections do
  resources :students
  end

  resources :uploads

  # necessary for dropzone to work, however this means that /uploads is a viable link which we don't want. TODO: address this
  post '/uploads' => 'uploads#create'

  root 'sections#index'

  get 'sections/:id/flashcards', to: "sections#flashcards", as: :section_flashcards

  get 'sections/:id/quiz', to: "sections#quiz", as: :section_quiz

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

classroom-dashboard/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :admin
  has_many :students

end

classroom-dashboard/app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  # Find the section ID before any other action
  before_action :find_section, only: [:show, :edit, :update, :destroy, :flashcards, :quiz]
  before_action :authenticate_admin!, only: [:new, :edit]


  def index
    @section = Section.all.order("semester DESC")
  end

  def show
  end

  def new
    @section = current_admin.sections.build
    # @section = Section.new
    # @section.admin_id = current_admin.id
  end

  def create
    @section = current_admin.sections.build(section_params)
    # @section = Section.new(section_params)
    # @section.admin_id = current_admin.id

    if @section.save
      redirect_to root_path
    else
      # Display form to input fields for new Section
      render 'new'
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    # If Section is updated successfully
    if @section.update(section_params)
      redirect_to section_path(@section)
    else
    # Display form to edit Section info
      render 'edit'
    end
  end

  def destroy
    @section.destroy
      redirect_to root_path
  end

  # only needs section passed in, handled in before_action
  def flashcards
  end

  # only needs section passed in, handled in before_action
  def quiz
  end



  private

    # Define what fields are required to edit or create a new Section
    def section_params
      params.require(:section).permit(:course, :semester, :year, :professor)
    end

    # Find the section by it's ID
    def find_section
      @section = Section.find(params[:id])
    end
  end

classroom-dashboard/app/helpers/sections_helper.rb
module SectionsHelper
end

classroom-dashboard/app/views/sections/_form.html.erb
<br>
<br>
<br>
<br>
<!-- fix this to better form once we meet with client -->

<!-- form for new and edit, loaded in new.html.erb -->
<!-- Fields prompted to the user to create a new Section -->
<%= simple_form_for @section do |f| %>
	<%= f.input :course, label: "Course (ex: CS5)" %>
	<%= f.input :semester, label: "Semester (ex:S2018)" %>
	<br>
	<%= f.button :submit %>
<% end %>

classroom-dashboard/app/views/sections/edit.html.erb
<!-- To edit Section fields, display form -->

<% if current_admin.id == @section.admin_id %>

  <div class="col-md-6 col-md-offset-3">

    <div class="new-section-form">
      <h1 class = edit_section_info> Edit Section </h1>

      <%= render 'form' %>
      <h5><%= link_to "Cancel", root_path %></h5>

      <h5 class = delete_section_link><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, section_path(@section), method: :delete, data: {confirm: "Are you sure?"} %></h5>

    </div>

  </div>

<% else %>

  <div class="error">
    <h2>Whoops!</h2>
    <br>
    <h3>It looks like you don't have access to that page. The green alien will redirect you...</h3>
  </div>

  <div class="style_alien_error">
    <%= image_tag("alien.png", :alt => "rss feed") %>
    <%= link_to image_tag("alien.png"), root_path %>
  <!-- </div> -->

<% end %>

classroom-dashboard/app/views/sections/flashcards.html.erb
<nav class="navbar navbar-default">
	<div class="container">

	    <ul class="nav navbar-nav navbar-left">
	      <a href="#"><%= link_to "Flashcards", section_flashcards_path(@section), {:class => "flashcard_button"}%></a>
	      &nbsp;
	      &nbsp;
	      &nbsp;
	      &nbsp;
	      &nbsp;

	      <a href="#"><%= link_to "Memory Game", section_quiz_path(@section)%></a>
	    </ul>

		  <div class="navbar-header">
	      <%= link_to @section.course + " " + @section.semester, section_path, class: "navbar-brand" %>
	    </div>

			<ul class="nav navbar-nav navbar-right">
	      <div style="text-align:right">
	        <a href="#"><%= link_to "Student List", section_path(@section)%></a>
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        <a href="#"><%= link_to "Add Student", new_section_student_path(@section)%></a>
	      </div>
	    </ul>
	</div>
</nav>

<!-- <h1> Flashcards </h1> -->

<h3 style="text-align: center;  font-family: 'Work Sans', sans-serif;
  font-weight: 400;font-size:40px"> Up Now:
	<br>
<div id="up-now" style="text-align: center"></div>
</h3>

<br>

<h4 style="text-align: center">Up Next:	        &nbsp;
	<button onClick="skip()"> skip </button>
  <div id="up-next" style="text-align: center; size:200px"></div>
</h4>

<div class="style_alien_flashcards">
  <%= image_tag("alien.png", :alt => "rss feed") %>
</div>

<div class="flashcard_responses">
		<%= image_tag("flashcard_responses.png", :alt => "rss feed") %>
</div>



<script>

	$(document).keydown(function(e) {
		if (e.keyCode == 39) {
			next();
		};
	});

	var student_list = <%= @section.students.all.order("RANDOM()").to_json.html_safe %>;
	var n = <%= @section.students.all.length %>;
	var i = 0;

	// initialize page
	upnow(i);
	if (n > 1) {
		upnext(i+1);
	}

	function next() {
		if (i < n-1) {
			i = i + 1;
		} else {
			i = 0;
			// reached the end, re-randomize
			student_list = <%= @section.students.all.order("RANDOM()").to_json.html_safe %>;
			student_list = student_list.sort(function(a, b){return 0.5 - Math.random()});
			n = <%= @section.students.all.length %>;
		}
		upnow(i);
		if (i == n-1) {
			// display nothing when new list about to be generated
			// TODO: better solution
			$("#up-next").html("");
		} else {
			upnext(i+1);
		}
	};

	// renders student i in #up-now div
	function upnow(i) {
		console.log(student_list[i].student_img_file_name == null);
		$("#up-now").html("<br>");
		// alien for no photo 
		if (student_list[i].student_img_file_name == null) {
			$("#up-now").append('<img src="/images/student_show/alien.png"/>');
		} else {
		// account for ID digits in image url
		if (student_list[i].id >= 100) {
			$("#up-now").append('<img src="/system/students/student_imgs/000/000/' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" />');
		}
		if (student_list[i].id >= 10) {
			$("#up-now").append('<img src="/system/students/student_imgs/000/000/0' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" />');
		}
		else {
			$("#up-now").append('<img src="/system/students/student_imgs/000/000/00' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" />');
		}
	}
		$("#up-now").append("<br> <br>");
		$("#up-now").append(student_list[i].firstName);
		$("#up-now").append(" ");
		$("#up-now").append(student_list[i].lastname);
	};

	// renders student i in #up-next div
	function upnext(i) {
		$("#up-next").html("<br>");
		$("#up-next").append(student_list[i].firstName);
		$("#up-next").append(" ");
		$("#up-next").append(student_list[i].lastname);
	};

	function skip() {
		if (i < n) {
			student_list.splice(i+1,1);
			n = n-1;
		} else {
			$("#up-next").html("");
		}
		upnext(i+1);
	};

</script>

classroom-dashboard/app/views/sections/index.html.erb
<!-- HOMEPAGE -->

<% if admin_signed_in?  %>

<!-- List each section and a link to that section's info and it's student list -->
	<nav class="navbar navbar-default">
		<div class="container">

			<div class="navbar-header">
				<%= link_to "Sections", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav navbar-right">
				<h5 class = add_new_section><%= link_to "Add Course Section", new_section_path %></h5>
			</ul>
		</div>
	</nav>

	<br>
	<br>
	<br>

	<table>
	  <tr>
	    <th>Sections</th>
	    <th></th>
	  </tr>


	<% @section.each do |section| %>
		 <% if section != nil then %>
		  <% if current_admin.id == section.admin_id %>
			    <tr>
			      <td><%= link_to section.course + " " + section.semester, section_path(section)%></td>
			      <td><center><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_section_path(section) %></center></td>
			    </tr>
			 <% end %>
		 <% end %>
	<% end %>
	</table>

	<% else %>

		<div class="style_alien">
			<%= image_tag("alien.png", :alt => "rss feed") %>
		</div>

		<div class="homepage_speechbubble">
			<%= image_tag("homepage-speech-bubble.png", :alt => "rss feed") %>
		</div>

		<div class="cilantro">
			<%= image_tag("cilantro.png", :alt => "rss feed") %>
			<%= link_to image_tag("cilantro.png"), "https://giphy.com/gifs/spam-xdnytp8742kg0/fullscreen" %>
		</div>

	<% end %>

classroom-dashboard/app/views/sections/new.html.erb
<!-- To create a new Section, display form to enter Section fields -->
<div class="col-md-6 col-md-offset-3">

  <div class="new-section-form">

    <h1 class = create_new_section>New Section</h1>

    <%= render 'form' %>
    <h5><%= link_to "Cancel", root_path %></h5>

  </div>

</div>

classroom-dashboard/app/views/sections/next.js.erb
alert("alert!");

classroom-dashboard/app/views/sections/quiz.html.erb
<nav class="navbar navbar-default">
	<div class="container">

	    <ul class="nav navbar-nav navbar-left">
	      <a href="#"><%= link_to "Flashcards", section_flashcards_path(@section)%></a>
	      &nbsp;
	      &nbsp;
	      &nbsp;
	      &nbsp;
	      &nbsp;
	      <a href="#"><%= link_to "Memory Game", section_quiz_path(@section), {:class => "memory_game_button"}%></a>
	    </ul>

		  <div class="navbar-header">
	      <%= link_to @section.course + " " + @section.semester, section_path, class: "navbar-brand" %>
	    </div>

			<ul class="nav navbar-nav navbar-right">
	      <div style="text-align:right">
	        <a href="#"><%= link_to "Student List", section_path(@section)%></a>
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        &nbsp;
	        <a href="#"><%= link_to "Add Student", new_section_student_path(@section)%></a>
	      </div>
	    </ul>
	</div>
</nav>

<div class="style_alien_quiz">
  <%= image_tag("alien.png", :alt => "rss feed") %>
</div>

<div class="quiz-instructions">
	<%= image_tag("memory-instructions.png", :alt => "rss feed") %>
</div>

<br>
<!-- <h1> Memory Game </h1> -->
<br>

<div style="text-align:center">
  <div id="name" style="visibility:hidden;" style="center"></div>
  <br>
  <br>
  <div id="image" style="center"></div>
</div>


<script>
$(document).keydown(function(e) {
	if (e.keyCode == 32) {
		reveal();
	} else if (e.keyCode == 39) {
		next();
	};
});

var student_list = <%= @section.students.all.order("RANDOM()").to_json.html_safe %>;
var n = <%= @section.students.all.length %>;
var i = 0;

render_student(i);


// renders student i in #up-now div
function render_student(i) {
	// skip students without photos
	if (student_list[i].student_img_file_name == null ) {
		i = i+1;
		render_student(i);
	};
	$("#name").html('<a href=/sections/' + student_list[i].section_id +'/students/' + student_list[i].id + '>' + student_list[i].firstName + " " + student_list[i].lastname+'</a>');
	$("#image").html("<br>");
	// account for ID digits in image url
	if (student_list[i].id >= 100) {
		$("#image").append('<a href=/sections/' + student_list[i].section_id +'/students/' + student_list[i].id + '><img src="/system/students/student_imgs/000/000/' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" /></a>');
	}
	if (student_list[i].id >= 10) {
		$("#image").append('<a href=/sections/' + student_list[i].section_id +'/students/' + student_list[i].id + '><img src="/system/students/student_imgs/000/000/0' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" /></a>');
	}
	else {
		$("#image").append('<a href=/sections/' + student_list[i].section_id +'/students/' + student_list[i].id + '><img src="/system/students/student_imgs/000/000/00' + student_list[i].id + '/student_show/' + student_list[i].student_img_file_name + '" /></a>');
	}
};

function reveal() {
    var x = document.getElementById("name");
    if (x.style.visibility === "hidden") {
        x.style.visibility = "visible";
    } else {
        x.style.visibility = "hidden";
    }
};


function next() {
	var x = document.getElementById("name");
	if (x.style.visibility === "visible") {
			x.style.visibility = "hidden";
	};
	if (i < n-1) {
		i = i + 1;
	} else {
		i = 0;
		// reached the end, re-randomize
		student_list = student_list.sort(function(a, b){return 0.5 - Math.random()});
	}
	render_student(i);
};

</script>

classroom-dashboard/app/views/sections/show.html.erb
<!-- Content that is displayed when a Section is clicked on -->
<!-- show's section's attributes, students, add student functionality, and edit/delete course functionality -->

<% if admin_signed_in? %>
	<% if current_admin.id == @section.admin_id %>

		<nav class="navbar navbar-default">
			<div class="container">

		    <ul class="nav navbar-nav navbar-left">
		      <a href="#"><%= link_to "Flashcards", section_flashcards_path(@section)%></a>
		      &nbsp;
		      &nbsp;
		      &nbsp;
		      &nbsp;
		      &nbsp;
		      <a href="#"><%= link_to "Memory Game", section_quiz_path(@section)%></a>
		    </ul>

				<div class="navbar-header">
		      <%= link_to @section.course + " " + @section.semester, section_path, class: "navbar-brand" %>
		    </div>

				<ul class="nav navbar-nav navbar-right">
		      <div style="text-align:right">
		        <a href="#"><%= link_to "Student List", section_path%></a>
		        &nbsp;
		        &nbsp;
		        &nbsp;
		        &nbsp;
		        &nbsp;
		        <a href="#"><%= link_to "Add Student", new_section_student_path(@section)%></a>
		      </div>
		    </ul>
			</div>
		</nav>

<!-- Display student information -->
		<table>
			<col width="30%">
			<col width="45%">
			<col width="18%">
			<col width="8%">
		  <tr>
		    <th></th>
		    <th>Student</th>
		    <th>School</th>
				<th></th>
		  </tr>

			<% if @section.students.length != 0 %>
				<% @section.students.each do |student|%>
				  <% if student != nil then %>
				    <tr>
				      <td><%= link_to image_tag(student.student_img.url(:student_index)), section_student_path(student.section_id, student)%></td>
				      <td><%= link_to student.firstName + " " + student.lastname, section_student_path(student.section_id, student) %></td>
							<td><%= student.school %></td>
				      <td><center><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_section_student_path(student.section_id, student) %></center></td>

				    </tr>
					<% end %>
				<% end %>
			<% end %>

	<% else %>

		<div class="error">
			<h2>Whoops!</h2>
			<br>
			<h3>It looks like you don't have access to that page. The green alien will redirect you...</h3>
		</div>

		<div class="style_alien_error">
			<%= image_tag("alien.png", :alt => "rss feed") %>
			<%= link_to image_tag("alien.png"), root_path %>
		</div>

	<% end %>
<% end %>
</table>